### ISSUE TITLE
Data availability

### ISSUE THREAD

**Issue by jamesholcomb** [appliedbinf/covid19-event-risk-planner#14]
Hi, are the daily/current datasets used by the front end at https://covid19risk.biosci.gatech.edu available?  I was hoping to avoid hosting my own server.

**Comment by ar0ch** [comment]
See the update_current.sh and update_daily.sh for how we get our US data:

https://github.com/appliedbinf/covid19-event-risk-planner/blob/master/COVID19-Event-Risk-Planner/update_current.sh

https://github.com/appliedbinf/covid19-event-risk-planner/blob/master/COVID19-Event-Risk-Planner/update_daily.sh 


And see the individual country makeDailyMaps*.R for their respective data sources. We don't have a public facing API that makes this data available all together since they're pulled from open data sources to begin with and we don't have the person bandwidth to maintain such a public service. There are definitely other organizations better positioned for such work 😅

**Comment by jamesholcomb** [comment]
Ok...since the generated data is not being made available, I'll give the Dockerfile a try.

**Comment by ar0ch** [comment]
The transform from raw data to risk predictions is pretty straight forward and doesn't require the whole app to recreate. It could really all be done in Excel. Have a look at the calc_risk function, the inputs are circulating cases (today's cases - 14 day's agos cases), population of the region the cases are from, and event size. We scale circulating cases by either (50/14) or (100/14) for ascertainment bias of 5 or 10 and to 'averaged' the case count for the last 10 days.

**Comment by jamesholcomb** [comment]
Ah that is promising...I will ETL the data sources and see if I can match the output values using your explanation.

**Comment by ar0ch** [comment]
@jamesholcomb 

Site - https://covid19risk.biosci.gatech.edu/usa_risk_counties.csv

Github- https://github.com/appliedbinf/covid19-event-risk-planner/blob/master/usa_risk_counties.csv?raw=true

They'll update automatically twice daily when the site updates
