### ISSUE TITLE
Changing the event size resets map zoom and pan

### ISSUE THREAD

**Issue by jeremy303** [appliedbinf/covid19-event-risk-planner#6]
When drilling down into the map to view county-level results, navigation is already somewhat awkward (slow rendering, two-finger pan gesture on Mac affects  zoom instead).  This is further complicated in that changing the event size will reset the map to full overview.  This makes it more challenging than necessary to obtain county-leven risk for different event sizes, or just explore the visualization.

Thanks for the good work!

**Comment by ar0ch** [comment]
Hi Jeremy,

Due to the massive (and awesome) response we've gotten over the last week the code in the repo is a little out of date as we made tweaks to deal with scaling.  We're currently no longer interactively creating the maps (as is suggested by the current code base) and instead using pre-rendered HTML files that get swapped out depending on the slider position.  Unfortunately, this breaks our ability to keep track of user scroll and zoom events but was necessary to support the thousands of concurrent user's we're seeing (I'm *sure* there's a javascript solution but we haven't had the time between other work to attempt one yet).

As for zoom wonkiness, here we're unfortunately at the mercy of leaflet and it's rendering/js.  If you've got a specific case where theres some friction, I can try and smooth out the edges but no guarantees -- I'm no js dev!

**Comment by jeremy303** [comment]
I certainly understand the realities of tradeoffs and congratulations on the awesome response.  I wish I could say that's a good problem to have, but alas...

Thanks for the great public service and good luck with your project!

**Comment by LucyMcGowan** [comment]
@ar0ch If this is something you want to pursue I believe you can actually access the current map locations / zoom via `input$MAPID_bounds` and `input$MAPID_zoom` (more here: https://rstudio.github.io/leaflet/shiny.html under "Map Events" header) and then when someone updates `input$event_size_map` you could use `setView(lng, lat, zoom = zoom_level)` for the map shown.

**Comment by ar0ch** [comment]
@LucyMcGowan Is this actually the case of the maps aren't a reactive Shiny object?  I don't think it is. We swap the maps via a reactive renderUI that is loading a pre-rendered html map in an iframe. So there's never a reactive binding created for the map events

**Comment by LucyMcGowan** [comment]
AH I didn't realize it was an iframe I was thinking it was rendered from this:

https://github.com/appliedbinf/covid19-event-risk-planner/blob/078498611b4ca2c5ae8842e5bbc9780508e717b3/COVID19-Event-Risk-Planner/server.R#L91-L96

**Comment by ar0ch** [comment]
Yeah, I've been bad about pushing the current code to github (😔). This week was a lot of putting out fires via tweaks to production as we saw thousands of visitors/min. The current application code should make it to github this weekend
